TerraCraft:
    Server:
        Name: NULL
        IP: NULL.Terra-Craft.net
        Mode: DEVELOPMENT
    Database:
        Hostname: 
        Database: 
        Port: 3306
        Username:
        Password: