name: TerraCraft
main: uk.co.terragaming.code.terracraft.TerraCraft
version: 0.0.2
commands:
    staff:
        description: Staff Command Set
        usage: /staff
    a:
        description: Staff Command Set
        usage: /a
    test:
        description: test
        usage: /test
    t:
        description: test
        usage: /test